version: '3'

services:
  web:
    build:
      context: ./web
      args:
        - VUE_APP_API_URL=http://localhost:5051
    ports:
      - 5050:80
    depends_on:
      - 'api'
  api:
    build:
      context: ./api
    ports:
      - 5051:80
    depends_on:
      - 'db'
    environment:
      - ClientHostName=localhost
      - ConnectionStrings__Budgeter=Host=localhost;Username=postgres;Password=postgres;Database=budgeter;
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - budgeter-db-data:/var/lib/postgresql/data:delegated

volumes:
  budgeter-db-data: